### ISSUE TITLE
flight_logger

### ISSUE THREAD

**Issue by graememilne** [CactusProjects/flight_logger#1]
Hi ,trying out your software which is interesting.   (http://cactusprojects.com/logging-dump1090-fa-to-local-database/)
                                                                                ( https://github.com/CactusProjects/flight_logger)

1. flight_logger is referred to as flightlogger in the code.
2. flightdata is referred to as flight_data in the code
3. When i checked cd /var/www/html/, there is index.html but no data.csv.
4. At first i could not get anything too work until i played about with 1. + 2.
5. Referring to number 3. do i require to set up the data.csv or does the script do that ???
6. How do i get the web page to show ???
7.  This post is broken into three un-linked sections:
     1. Logging all flights to .csv file.
     2. Deciding csv was not ideal and move logging to database SQLite (incl. setup).
     3. Solution to show all days flights on webpage.
 8.  Looking at what i have just written does the scripts works 1+2+3 or 1+3 or 2+3 ( i suspect 2+3 )
 9. Could you clarify these to me ,please and thank you.     
 
 Look forward to your reply
Graeme

**Comment by CactusProjects** [comment]
Hi, sorry for the code disaster, that's what happens when no computer science background!

1.     flight_logger is referred to as flightlogger in the code.
- Thanks I updated repo name as easiest way to fix.

2.     flightdata is referred to as flight_data in the code
- Could not figure this out, I have db called fightdata & table called flight_data and seems to be fine?

3.     When i checked cd /var/www/html/, there is index.html but no data.csv.
- Added instruction that user has to create this.

5.     Referring to number 3. do i require to set up the data.csv or does the script do that ???
- Added instruction that user has to create this.

6.     How do i get the web page to show ???
- Just enter IP address of device or localhost on the unit itself

8.     Looking at what i have just written does the scripts works 1+2+3 or 1+3 or 2+3 ( i suspect 2+3 )
- I updated this but yes 1 is standalone and 2+3 work together
